REVIEW - Importer costbasis improvements
AUGMXNT/perfi pull request #4
Opened 2022-06-21 13:30 UTC by peloriante

Not ready for a merge until we update Kraken importer to pass price_usd for trades (when it can)

2022-07-06 10:10 UTC, lhl requested changes

2022-07-06 10:10 UTC, lhl commented on perfi/transaction/chain_to_ledger.py
> +                # Costbais code downstream wants price_usd to represent the unit price, so we divide total gas fee by amount here
typo: Costbasis

2022-07-06 10:10 UTC, lhl commented on tests/integration/test_imports_from_exchanges.py
> +User,gabe@avantbard.com,530c49d9e612ded0020002b8
PII

2022-07-06 10:10 UTC, lhl commented on tests/integration/test_imports_from_exchanges.py
> +            hash="import.coinbase_1488610341_Receive_btc",
fuzz all ids

2022-07-06 10:11 UTC, lhl commented
Once scrubbing PII from checkin history, remember to scrub this pull req

2022-07-07 01:34 UTC, peloriante commented on tests/integration/test_imports_from_exchanges.py
> +            hash="import.coinbase_1488610341_Receive_btc",
1488610341  is a timestamp

2022-07-07 01:35 UTC, peloriante commented on perfi/transaction/chain_to_ledger.py
> +                # Costbais code downstream wants price_usd to represent the unit price, so we divide total gas fee by amount here
fixed

2022-07-07 01:38 UTC, peloriante commented on perfi/costbasis.py
> -            sql += "ORDER BY cast(price_usd as float) DESC, timestamp ASC"
fixed

2022-07-07 01:38 UTC, peloriante commented on perfi/costbasis.py
> -            sql += "ORDER BY cast(price_usd as float) ASC"
fixed

2022-07-07 06:41 UTC, merged